name: rogue
version: 0.0.1
authors:
- Jannik Schwardt
- Ruben Maurer

description: A rogue like dungeon crawler in dart
homepage: https://github.com/Schrotty/DartRogue

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  start: ">=0.2.7 <0.3.0"
  collection: "1.14.6"